[package]
name = "example-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
warp = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
